name: dotnet build

# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

on: 
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      # - name: Install curl
      #   run: |
      #     apt-get update; apt-get install -y curl libicu
      - uses: actions/checkout@v3
      # - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./src/
      - name: Build
        run: dotnet build --configuration Release --no-restore ./src/
      - name: Test
        run: dotnet test --no-restore --verbosity normal ./src/
      - name: Pack
        run: dotnet pack --configuration Release -o . --include-symbols ./src/